name: Build Panel

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          submodules: 'recursive'

      - name: restore ccache
        id: ccache
        uses: actions/cache@v2
        with:
          path: ${{ runner.temp }}/ccache
          # "github.run_id" is unique, which causes the cache to always get
          # saved at the end of a successful run.
          key:  ccache-panel-${{ github.ref }}-${{ github.run_id }}
          # As the unique "key" above will never be found in the cache when the
          # job starts, we need these broader "restore-keys" in order to match
          # and restore the most recent cache.
          restore-keys: |
            ccache-panel-${{ github.ref }}-
            ccache-panel-
      
      - name: configure ccache
        run: |
          ccache --set-config sloppiness=file_macro,time_macros
          ccache --set-config cache_dir='${{ runner.temp }}'/ccache
          ccache --set-config compression=true
          ccache --set-config max_size=1G
          ccache -s
        
      - name: extract Qt
        run:
          mkdir -p /home/runner/work/QtSnapshot/QtSnapshot
          curl -L https://github.com/moodyhunter/QtSnapshot/releases/download/qt-dev/qt-host.7z -o qt-host.7z
          curl -L https://github.com/moodyhunter/QtSnapshot/releases/download/qt-dev/qt-wasm.7z -o qt-wasm.7z
          7z x -o/home/runner/work/QtSnapshot/QtSnapshot ./qt-host.7z
          7z x -o/home/runner/work/QtSnapshot/QtSnapshot ./qt-wasm.7z
          /home/runner/work/QtSnapshot/QtSnapshot/wasm-installed/bin/qmake --version
